### PR TITLE
Improve RedPen custom resource loading

### PR DESCRIPTION
**Pull request by cbxp**
Custom resources will now be looked for from 3 places:

* Working directory
* Relative to the config file (new feature)
* From REDPEN_HOME directory

All Validators now have access to this functionality via Validator.findFile().
All existing validators were updated to use it.

**WARNING:** This pull request depends (contains the same changes) on this one https://github.com/redpen-cc/redpen/pull/550, please merge #550 first.

Review changes starting from this commit: https://github.com/codeborne/redpen/commit/042cfdc9a072ff64513780f17b87c848930fa53f

### CODE REVIEW

**Comment by takahi-i** [comment]
Hmm... Removing ensureFileIsInsideRedPenHomeOrWorkingDirectory looks unsafe... 

@yusuke Can you please tell me your idea on the changes?

**Comment by cbxp** [comment]
findFile() already looks in particular places to resolve the files or throws the same exception as ensureFileIsInsideRedPenHomeOrWorkingDirectory() did if the file is not found. There seems to be no other reason of restricting where the files should be located, isn't it? The method looked obsolete to us.

**Comment by takahi-i** [comment]
https://github.com/redpen-cc/redpen/pull/551/files#diff-c16ea514f3a38d77d53f9165b08daedbR149

I see. you are right.

**Comment by takahi-i** [comment]
I would like to know where is tests for restricting the js directory is throwing the exception.

**Comment by cbxp** [comment]
We have added the missing tests

**Comment by takahi-i** [comment]
Thanks!

**Pull request merged**
