### PR TITLE
simplify ValidatorFactory using reflections lib.

### PR DESCRIPTION
**Pull request by yusuke**
simplify ValidatorFactory using reflections lib.

### CODE REVIEW

**Comment by takahi-i** [comment]
Cool!

**Comment by takahi-i** [comment]
LGTM

**Comment by takahi-i** [comment]
oops! i forgot to merge this pull request...

**Comment by gerryhocks** [comment]
Currently when I run redpen-server there are no validators in the war file.
Is it possible that this merge stopped the individual validator classes from being included in the war file built for redpen-server because there was no explicit reference in the code path used by the server?

I will investigate but was wondering if you saw the same sort of thing when running the GUI?

**Comment by takahi-i** [comment]
I see the status there is no validators.
 
http://redpen.herokuapp.com/

**Comment by gerryhocks** [comment]
So it is not just me :) 

I will see what I can do to ensure the Validator classes get included in the war file

**Comment by takahi-i** [comment]
Thanks!

**Comment by gerryhocks** [comment]
I managed to get it working.. the lazy load that only loaded the validators when a document was processed (and each time it is processed) seemed to mean that the validators could not be found prior to a validation being performed.

The pull request that updates the error suppression code includes this patch.

**Comment by takahi-i** [comment]
Thanks!

**Pull request merged**
