### PR TITLE
Implement basic Korean support

### PR DESCRIPTION
**Pull request by raccoonyy**
Hello. I implemented basic Korean support for proofreading Korean. I referred to #568 and added Korean morphological analyzer Komoran as a dependency.

This P.R. based on @nacyot's https://github.com/redpen-cc/redpen/pull/784 .

### CODE REVIEW

**Comment by takahi-i** [comment]
👍

**Comment by takahi-i** [comment]
@raccoonyy Thank you very much for the valuable contributeion! I will look into the changes.

**Comment by takahi-i** [comment]
Deeply sorry for the late response... I will review this PR this weekend.

**Comment by raccoonyy** [comment]
Thanks! 👍

**Comment by raccoonyy** [comment]
I will add the docs soon. Thanks. :)

**Comment by raccoonyy** [comment]
@takahi-i I added sample documents. I'm really sorry for the late.

**Comment by takahi-i** [comment]
Thank you very much @raccoonyy ! I will look into the changes this weekend.

**Comment by takahi-i** [comment]
LGTM. Can you grant these changes under the Apache License 2.0 @raccoonyy?

**Comment by raccoonyy** [comment]
@takahi-i Yes I do. :)

Do I have to modify the docs to grant Apache License 2.0?

**Comment by takahi-i** [comment]
Thank you for the agreement @raccoonyy! 

> Do I have to modify the docs to grant Apache License 2.0?

Nothing. We just confirm it when large feature is proposed.

Thank you very much for the consistent work!

**Pull request merged**
