### PR TITLE
Enhance VoidSectionValidator

### PR DESCRIPTION
**Pull request by midnightSuyama**
Add subsection exist  of VoidSectionValidator.

## New property

* subsection

### Document file (*.md)

```
# Section

## SubSection 1

paragraph 1

## SubSection 2

paragraph 2
```

### Configuration file

```
        <validator name="VoidSection">
            <property name="subsection" value="true"/>
        </validator>
```

### CODE REVIEW

**Comment by takahi-i** [comment]
Thank you for the contribution @midnightSuyama. I do not understand the usage of the new parameter, *subsection*. For filtering the levels of sections (section, subsection, subsubsection) is already provided another parameter **limit**.

Also the parameter name, subsection is a ambiguous. For example subsection of Markdown is set by level 2 but subsection of LaTeX could be 3 (chapter >  section > subsection).

**Comment by midnightSuyama** [comment]
@takahi-i Thanks, I see. New property is validator of exist other than paragraph.

## Case 1

```
# Section

paragraph
```

```
        <validator name="VoidSection">
        </validator>
```

`# Section` is valid.

## Case 2

```
# Section

## Subsection

paragraph
```

```
        <validator name="VoidSection">
        </validator>
```

`# Section` is invalid. `## Subsection` is valid.
Because, `# Section` has no paragraph, but has subsection.

## Case 3 (Enhance)

```
# Section

## Subsection

paragraph
```

```
        <validator name="VoidSection">
            <property name="subsection" value="true"/>
        </validator>
```

`# Section` and `## Subsection` is valid.
Because, `# Section` has subsection, and is not empty.

I was worried about property name. Alternatives were `has_section`, `has_subsection`, `is_subsection` and `exist_subsection`.

Thanks :)

**Comment by takahi-i** [comment]
Thank you very much for the detailed description on the pull request @midnightSuyama! I fully understand the meaning.  

I am not able to merge this pull request since this PR break the basic policy  of this validator (VoidSectionValidator). I  made this validator to check if the top level sections or chapter contains self introduction.  The following an example of self introduction.

```


``` 


The topic is discussed in  [a thread in StackExchange](http://academia.stackexchange.com/questions/63162/is-it-okay-to-begin-a-chapter-without-an-introduction-section).

**Comment by midnightSuyama** [comment]
@takahi-i Understood. I learned from your knowledge. Thanks!

**Pull request closed without merging**
