### PR TITLE
Adds VoidSectionValidator

### LINKED ISSUE #606: Void Section validator
Section should have some contents at least one line.

### PR DESCRIPTION
**Pull request by taky**
Hello, I've added VoidSectionValidator, a validator looks for void sections.
This PR intends to resolve #606.

Please review and hopefully merge.
Thanks.
-t

Changes:
- src/main/resources/cc/redpen/validator/section/error-messages.properties: Adding the message.
- src/main/resources/cc/redpen/validator/section/error-messages_ja.properties: Adding the message.

### CODE REVIEW

**Comment by takahi-i** [comment]
Thank you very much for the contribution @taky!  How about there is a paragraph with void sentence? Some parser could create such sections.

**Comment by taky** [comment]
Thanks for your comment -- now it catches sections that do not hold any paragraph with actual sentences.

**Comment by taky** [comment]
Rebased onto the current master.

**Comment by takahi-i** [comment]
Thanks!

**Pull request merged**
