### PR TITLE
Allowing non-top headers to start document

### LINKED ISSUE #657: GappedSection flush many errors when files are imported

### PR DESCRIPTION
**Pull request by taky**
Hello, I've fixed GappedSection so that it allows non-top headers to start document.
This PR intends to resolve #657.
Please review and merge.
Thanks.
-t

Changes:
- redpen-core/src/main/java/cc/redpen/validator/section/GappedSectionValidator.java: Latching on the first header level.
- redpen-core/src/test/java/cc/redpen/validator/section/GappedSectionValidatorTest.java: Added test case.

### CODE REVIEW

**Comment by takahi-i** [comment]
👍

**Comment by takahi-i** [comment]
Thanks but I got many errors... with the following configuration for RedPen Japanese document.

---
<redpen-conf lang="ja">
  <validators>
    
    <validator name="SentenceLength">
      <property name="max_len" value="100"/>
    </validator>
    <validator name="CommaNumber" />

    
    <validator name="KatakanaEndHyphen">
    <validator name="KatakanaSpellCheck" />
      <property name="list" value="ポリシー,トラッカー" />
    </validator>
    <validator name="SuggestExpression">
      <property name="dict" value="redpen_resources/terminologies.txt" />
    </validator>
    <validator name="JapaneseStyle" />
    <validator name="InvalidExpression" />
    <validator name="DoubleNegative" />
    <validator name="FrequentSentenceStart" />
    <validator name="Okurigana"/>
    <validator name="JapaneseNumberExpression"/>
    <validator name="JapaneseAnchorExpression"/>
    <validator name="JapaneseAmbiguousNounConjunction" />
    <validator name="LongKanjiChain" />

    
    <validator name="SuccessiveWord" />

    
    <validator name="SectionLength">
      <property name="max_num" value="1500"/>
    </validator>
    <validator name="ParagraphNumber"/>
    <validator name="SectionLevel" />
    <validator name="GappedSection" />

    
    <validator name="InvalidSymbol"/>
    <validator name="SpaceBetweenAlphabeticalWord" />
    <validator name="ParenthesizedSentence">
      <property name="max_count" value="2"/>
      <property name="max_nesting_level" value="1"/>
      <property name="max_length" value="10"/>
    </validator>

    
    <validator name="JavaScript">
      <property name="script-path" value="js"/>
    </validator>
  </validators>
  <symbols>
    <symbol name="FULL_STOP" value="。" invalid-chars="．" />
    <symbol name="QUESTION_MARK" value="？" />
    <symbol name="COMMA" value="、" invalid-chars="，"/>
    <symbol name="COLON" value="：" />
    <symbol name="DOLLAR_SIGN" value="＄" />
    <symbol name="LESS_THAN_SIGN" value="＜" />
    <symbol name="GREATER_THAN_SIGN" value="＜" />
    <symbol name="VERTICAL_BAR" value="｜" />
  </symbols>
</redpen-conf>
---

**Comment by takahi-i** [comment]
The followings are the errors from the GappedSection

```
validator_ja.adoc:401: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: JapaneseStyle
validator_ja.adoc:406: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: 対応言語
validator_ja.adoc:411: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: DoubleNegative
validator_ja.adoc:416: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: 対応言語
validator_ja.adoc:421: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: FrequentSentenceStart
validator_ja.adoc:425: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: プロパティ
validator_ja.adoc:436: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: 対応言語
validator_ja.adoc:441: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: UnexpandedAcronym
validator_ja.adoc:450: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: プロパティ
validator_ja.adoc:459: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: 対応言語
validator_ja.adoc:464: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: WordFrequency
validator_ja.adoc:469: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: プロパティ
validator_ja.adoc:479: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: Supported languages
validator_ja.adoc:484: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: Hyphenation
validator_ja.adoc:489: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: Supported languages
validator_ja.adoc:494: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: NumberFormat
validator_ja.adoc:499: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: プロパティ
validator_ja.adoc:509: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: 対応言語
validator_ja.adoc:514: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: ParenthesizedSentence
validator_ja.adoc:524: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: プロパティ
validator_ja.adoc:535: ValidationError[GappedSection], The section "4" (level 1) is misplaced. It should have level of {2}. at line: 対象言語
validator_ja.adoc:540: ValidationError[GappedSection], The section "3" (level 1) is misplaced. It should have level of {2}. at line: WeakExpression
```

**Comment by taky** [comment]
Oops.. thanks.  I'll take a closer look.

**Comment by taky** [comment]
The issue should be now fixed.

**Comment by takahi-i** [comment]
LGTM

**Pull request merged**
