### PR TITLE
SuggestExpressionValidator should do whole matches only

### PR DESCRIPTION
**Pull request by cbxp**
Otherwise if it suggests changing of "info" to "information", then it reports "**info**rmation" as error again.

### CODE REVIEW

**Comment by takahi-i** [comment]
@cbxp in my understanding this does not work for Japanese or Chinese texts since the words are not  explicitly split in these languages.

**Comment by takahi-i** [comment]
The detection should be based on phrase level not words.

**Comment by takahi-i** [comment]
For the usage I suggest to make another token based validator, SuggetWord.

**Comment by cbxp** [comment]
We have made another fix that looks for word boundaries around the expression. For Japanese validator works as before.

**Comment by takahi-i** [comment]
@cbxp i would like you to try writing blog post of intellij plugin before fixing bugs.

**Comment by cbxp** [comment]
We found these bugs while writing the tutorial. Now it is done, but bugs are still there :-)

**Comment by takahi-i** [comment]
Thanks!

**Comment by cbxp** [comment]
We rebased this fix onto new master. The latest code still works with whole expressions.

**Comment by takahi-i** [comment]
Excellent!

**Pull request merged**
