### PR TITLE
Porting the long-kanji-chain.js validator

### LINKED ISSUE #588: Porting JS-based validator: long_kanji_chain.js

### PR DESCRIPTION
**Pull request by taky**
Hello, I have ported the long-kanji-chain.js validator.
It detects long kanji chains (i.e. complex jyukugos.)
This PR intends to resolve #588 .

Please review and hopefully merge.
Thanks.
-t

Changes:
- redpen-core/src/main/resources/cc/redpen/validator/sentence/error-messages.properties: Added messages.
- redpen-core/src/main/resources/cc/redpen/validator/sentence/error-messages_ja.properties: Added messages.

### CODE REVIEW

**Comment by taky** [comment]
(branch restored.)

**Comment by taky** [comment]
(branch restored.)

**Comment by takahi-i** [comment]
Should this validator be registered in ValidatorFacrory?   @taky

**Comment by taky** [comment]
Oops, I'll fix that.

**Pull request merged**
