### PR TITLE
Prepare for using Kuromoji being from Maven Central

### PR DESCRIPTION
**Pull request by cmoen**
We are planning on publishing Kuromoji to Maven Central soon.  As part of this, it would be great to test it in a few projects before we release it.  This pull-requests contains changes that uses `kuromoji-ipadic` from the release candidate from Sonatype's staging repository.

### CODE REVIEW

**Comment by takahi-i** [comment]
:+1:

**Comment by johtani** [comment]
+1

**Comment by cmoen** [comment]
I need to double-check the repository details.  My apologies that this pull-request didn't build properly...

**Comment by cmoen** [comment]
I'm merging this. Let's let Kuromoji bake a bit in RedPen before we push it to Maven Central. Once pushed, I'll update the POM to use the officially released version.

**Pull request merged**
