### PR TITLE
Support Portable Object (.po) parser

### PR DESCRIPTION
**Pull request by kenhys**
It is useful if RedPen supports portable object by default because it can support technical documents which are translated by gettextize mechanism.

### CODE REVIEW

**Comment by takahi-i** [comment]
:+1:

**Comment by takahi-i** [comment]
Hello @kenhys. 

Deeply sorry for the late response and thank you very much for the pull request on the Portable Object parser!

It would be appreciate it if you tell us the url for the specification page of Portable Object format, since I do not know the format.. 

I have read the parser for the Portable Object and understand the implementation. The implementation itself is nice, but we would like to add more and more tests for the parser to maintain the parser for the future releases. I think the tests of Wiki parser is a good example, since both parsers (Wiki and current PO) does not supports position offsets.

The following is the tests of Wiki parser.

- Tests for list elements (if PO support list bloc)
- Tests for sections (if PO support sections)
- Tests for comments (if PO support sections)
- Tests for multiple paragraphs
- Tests for handling to links (if PO supports links such as RST or Markdown)

In addition, would be helpful if you add test for tricky sentences as follows.
- Tests for sentence which are wrapped into more than two lines (such as “that is a apple. this is ¥n a pen. the other is oranges.”)
- void document

**Comment by kenhys** [comment]
> It would be appreciate it if you tell us the url for the specification page of Portable Object format, since I do not know the format..

I don't know official spec about the format, but as far as I know, following the URL is good reference manual.
http://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/PO-Files.html

It is good thing to add more test cases, because this PR implements very tiny test case.
I'll try it later.

MEMO:
 At first, I've searched existence po parser, https://launchpad.net/po-parser, but It adopts GPLv3 and I doubt that that project is still maintained.
Secondly, I've considered to use external tool such as msgfmt. It converts from po to .class(ResourceBundle), but it drops position property, so I've threw away it. so I've dare to implement very limited set of po parser for it.

**Comment by takahi-i** [comment]
Thank you a lot for the information on PO!

**Comment by cbxp** [comment]
We vote for merging of this pull request - it adds support for a popular (in Python and C world) localization file format provided by gettext library.

**Comment by takahi-i** [comment]
I will close this issue for now. Let me close this issue for now and would be appreciate it if you send another issue after you finished the tests.

**Pull request closed without merging**
